CREATE TABLE CUSTOMER (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	customer_name varchar(255) not null,
	contact_number varchar(255) not null,
	address varchar(255) not null,
	gender varchar(255) not null
);